[[entry]]
question = "How do I use any tool?"
answer = "Most tools work by changing the .osu file of your beatmap. Make sure you set the correct path to your beatmap (visible on the bottom blue bar) using the options in the file menu. Then run the tool by clicking the play button on the bottom left. After running the tool always reload the editor (Ctrl+L) so the changes to the .osu show up in the editor. You can also look in the documentation to find some tutorials."

[[entry]]
question = "Hitsound Copier spammed unwanted volume changes."
answer = "The 'Overwrite only defined' mode preserves the hitsounds of anything not defined in the hitsound diff including volumes. That's why it goes back to the original volume on every unhitsounded sliderend for example. To fix this you just have to use the 'Overwrite everything' mode and copy over only the volumes. You can still preserve muted sliderends while using 'Overwrite everything' by enabling 'Always preserve 5% volume'."

[[entry]]
question = "A tool broke my map forever. What do I do?"
answer = "By default, Mapping Tools always makes a backup of any map that gets edited. You can find these backups by clicking Options -> Open backup folder."

[[entry]]
question = "Get current beatmap doesn't work."
answer = "Make sure you set the right path to your Songs folder in the Preferences window."

[[entry]]
question = "I have a question not on this list or I found a bug."
answer = "Go to the mapping-tools-techsupport channel in this Discord, ask me directly on Discord (OliBomby#3573) or make a new issue on the GitHub."
