name: Release

on:
  push:
    tags:
      - "v*.*.*"
      
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore Mapping_Tools_Net5
      
    - name: Build
      run: dotnet build Mapping_Tools_Net5 -c Release --no-restore
      
    - name: Test
      run: dotnet test Mapping_Tools_Net5 --no-build --verbosity normal
      
    - uses: papeloto/action-zip@v1
      with:
        files: Mapping_tools_Net5/bin/Release/net5.0-windows/
        dest: release.zip

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          release.zip